### PR TITLE
Add `kVariantHK.txt`

### PR DESCRIPTION
**Pull request by graphemecluster**

### CODE REVIEW

**Comment by graphemecluster** [comment]
The second commit is added assuming that `kVariantHK.txt` is applied on top of `kVariants.txt`.

**Review by hfhchan — CHANGES_REQUESTED** [review]
Can you convert all classifications to "→"? 

For 兑 昷 户 please use "↔", as both characters are often used -- the left codepoint being the big-5 codepoint and the right codepoint being the HKSCS codepoint.

I think we can add 告 ↔ 吿 pair as well even though the kVariants list canonicalizes to 吿, so this list would also be useful in its own context.

I will add a readme file explaining the usage and caveats.

**Comment by hfhchan** [comment]
I will update the classification in kVariants separately by script. Also we will need to ping meilisearch to release a new version of the rust crate.

**Comment by graphemecluster** [comment]
Lines that are only in [OpenCC HKVariants.txt](https://github.com/BYVoid/OpenCC/blob/5750d92a92ac1f2d64c880c1f6f1a5e382d7d199/data/dictionary/HKVariants.txt) (some lines are not even related though):
```
叄	叁
只	只 衹
妝	妝 粧
擡	抬
敘	敍 敘
棱	稜 棱
檯	枱
溼	濕
癡	痴
皁	皂
祕	秘
竈	灶
糉	粽 糉 糭
纔	才
臺	台
菸	煙
蔥	葱
覈	核
踊	踴
鉢	缽
鉤	鈎
鍼	針
```

Lines that are not in OpenCC HKVariants.txt:
```
値	值
偸	偷
兪	俞
卽	即
告	吿
啓	啟
喞	唧
喩	喻
塡	填
姸	妍
尙	尚
廏	廄
强	強
愼	慎
敎	教
旣	既
曁	暨
査	查
楡	榆
槪	概
淸	清
漑	溉
煕	熙
眞	真
硏	研
緖	緒
繦	繈
詽	訮
豣	豜
鄕	鄉
鎭	鎮
靑	青
𣽸	滘
```

Chaak added but missing currently:
```
宂	冗
````

**Pull request merged**
